// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bykatxsxjosmgxpiatvq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5a2F0eHN4am9zbWd4cGlhdHZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2MTkyMTAsImV4cCI6MjA1ODE5NTIxMH0.QwEeRVjdCzDMRmc9-wNOGEJ3-wnbNZz7rsS74cTtF9Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);